### ISSUE TITLE
python docker_pull.py centos -> KeyError: 'layers'

### ISSUE THREAD

**Issue by reddiana** [NotGlop/docker-drag#1]
Thanks for this wonderful script.
But I have encountered the following problem.
```
(python2) C:\Users\red.suh>python docker_pull.py centos
Traceback (most recent call last):
  File "docker_pull.py", line 40, in <module>
    layers = resp.json()['layers']
KeyError: 'layers'
```
For nginx or sonatype/nexus3, there is no problem.
How can I solve the problem?
Thanks

**Comment by NotGlop** [comment]
I have tried it, but I don't have the error:
```
C:\Users\notglop>python docker_pull.py centos
Creating image structure in: tmp_centos_latest
8ba884070f61: Pull complete [75403831]
Docker image pulled: library_centos.tar
```

Not finding the "layers" field in the manifest would be weird. Which version of python/requests/json are you using?
Also, I have checked centos manifest and there is indeed one layer in the "layers" section so it shouldn't fail.
I guess you received an invalid HTTP response somehow.
Could you put this line of code (line 40, before the faulting line) and retry:
`print resp.content`

Do you receive the manifest or anything else?

**Comment by reddiana** [comment]
Thank you for taking a look.
I tried centos again and embarrassingly the script works well.
Perhaps it was a company proxy issue.
This wonderful script is very helpful to me and my colleagues.
Thank you.

**Comment by NotGlop** [comment]
Thank you for your feedback. I'm glad to hear it.
Closing the issue.

**Comment by golimarrrr** [comment]
I get this same error with https://hub.docker.com/r/nitnelave/lldap
I tried on Cygwin and on Debian12, should the script work with this repository?

**Comment by afkzoro** [comment]
I also get the same error. Can anyone help?
