### ISSUE TITLE
Big files(e. g. gitlab/gitlab-ce:12.3.7-ce.0) aren't supported

### ISSUE THREAD

**Issue by idoktorova** [NotGlop/docker-drag#11]
Logs:

```
Creating image structure in: tmp_gitlab-ce_12.3.7-ce.0
e80174c8b43b: Pull complete [44144090]
d1072db285cc: Pull complete [529]
858453671e67: Pull complete [849]
3d07b1124f98: Pull complete [170]
655fb0f51b08: Pull complete [26257584]
063c37e78c5c: Pull complete [141]
a0398d68068f: Pull complete [146]
f41e790a20a6: Pull complete [236]
8eb8c4ceb762: Pull complete [4095]
e3a502127d8c: Pull complete [705893899]
Traceback (most recent call last):
  File "docker_pull.py", line 129, in <module>
    file.write(unzLayer.read())
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\gzip.py", li
ne 276, in read
    return self._buffer.read(size)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\gzip.py", li
ne 471, in read
    uncompress = self._decompressor.decompress(buf, size)
MemoryError
```

**Comment by NotGlop** [comment]
Thank you for the issue. This should be fixed thanks to the stream download feature planned in https://github.com/NotGlop/docker-drag/pull/6

**Comment by DavoBR** [comment]
> Logs:
> 
> ```
> Creating image structure in: tmp_gitlab-ce_12.3.7-ce.0
> e80174c8b43b: Pull complete [44144090]
> d1072db285cc: Pull complete [529]
> 858453671e67: Pull complete [849]
> 3d07b1124f98: Pull complete [170]
> 655fb0f51b08: Pull complete [26257584]
> 063c37e78c5c: Pull complete [141]
> a0398d68068f: Pull complete [146]
> f41e790a20a6: Pull complete [236]
> 8eb8c4ceb762: Pull complete [4095]
> e3a502127d8c: Pull complete [705893899]
> Traceback (most recent call last):
>   File "docker_pull.py", line 129, in <module>
>     file.write(unzLayer.read())
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\gzip.py", li
> ne 276, in read
>     return self._buffer.read(size)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\gzip.py", li
> ne 471, in read
>     uncompress = self._decompressor.decompress(buf, size)
> MemoryError
> ```

Change this line 
https://github.com/NotGlop/docker-drag/blob/69b2bae59c6c0a5cbdf224feb9c067e3edcc6068/docker_pull.py#L154

for this: 

```py
shutil.copyfileobj(unzLayer, file)
```
