### ISSUE TITLE
Windows not supported

### ISSUE THREAD

**Issue by priyanksaini2010** [NotGlop/docker-drag#16]
![image](https://user-images.githubusercontent.com/608478/79065461-11164200-7cce-11ea-994c-c87b30a9d27a.png)

**Comment by NotGlop** [comment]
Obviously centos is a Linux image and you are surely using Docker for windows.  
Therefore, you need to switch between Windows and Linux containers. (see docker desktop documentation for that)

**Comment by priyanksaini2010** [comment]
Thanks It worked
