### ISSUE TITLE
Use with authorization needed registry

### ISSUE THREAD

**Issue by sebvieux** [NotGlop/docker-drag#18]
Hi any possibilities to use this script with authorization needed registry ? Thanks

**Comment by NotGlop** [comment]
Hello, the script already supports custom registries.  
If you want you can use it like that:  
docker_pull.py custom-registry:custom-port/repo/image

The script should handle the authorization by itself, thanks to your custom registry response's headers (as defined in Docker HTTPS API specification)

**Comment by NotGlop** [comment]
Closing the issue, since the script should already handle "authorization needed registries".
