### ISSUE TITLE
Fake layer ids

### ISSUE THREAD

**Issue by bduman** [NotGlop/docker-drag#19]
Hi,

I am currently porting this tool to .net core tool platform. So i have experiment about some cases.
That layer hashes calculated with sha256(layer.tar).

Also, recalculate layers when load image.tar

Could you check this ?

**Comment by NotGlop** [comment]
Just to bring an answer for information: fake layer IDs are just for building the archive (to guarantee an order in the tarball).  

Those layer IDs are NOT the real layer IDs displayed in Docker (which are correctly retrieved from the archive downloaded, by the way).
Hope this answers the question
