### ISSUE TITLE
repository full name is not reserved

### ISSUE THREAD

**Issue by Haffon** [NotGlop/docker-drag#23]
This is good tool. The docker host linux machine in my office doesn't have internet access. I used this tool to download the docker image from docker hub in windows machine which has internet access. It works great.
But I want this tool keep the repository full name for me. I hope the repository name is just same as docker hub after I load the tar file to docker engine, maybe some good repository name format policy would apply inside this tool?
Below is my operations:
```
> python docker_pull.py library/nginx:1.19.3-alpine
Creating image structure in: tmp_nginx_1.19.3-alpine
188c0c94c7c5: Pull complete [2796860]
61c2c0635c35: Pull complete [6761747]
378d0a9d4d5f: Pull complete [601]
2fe865f77305: Pull complete [897]
b92535839843: Pull complete [664]
Docker image pulled: library_nginx.tar
```
Then I renamed  library_nginx.tar to library_nginx-1.19.3-alpine.tar and upload it to linux machine which installed docker engine.
```
$ sudo docker load -i library_nginx-1.19.3-alpine2.tar
ace0eda3e3be: Loading layer [==================================================>]  5.843MB/5.843MB
4daeb7840e4d: Loading layer [==================================================>]  17.45MB/17.45MB
835f5b67679c: Loading layer [==================================================>]  3.072kB/3.072kB
d0e26daf1f58: Loading layer [==================================================>]  4.096kB/4.096kB
8d6d1951ab0a: Loading layer [==================================================>]  3.584kB/3.584kB
Loaded image: nginx:1.19.3-alpine
$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               1.19.3-alpine       4efb29ff172a        13 days ago         21.8MB
```
As you can see the "library/" section is lost in REPOSITORY name.

**Comment by Haffon** [comment]
I want to note some image full name is reservered, like rancher/coredns-coredns:1.6.9.

**Comment by NotGlop** [comment]
Thank you for your comment and feedback. 

**Library** is the default repository name of github.com (where official images are pushed).
Docker client never displays "library" repository as this is the default, so let's stick to that native Docker behavior.

This is why you see other non-default repository names, and also non-default registry names when you download your image from other repositorie; this is for understanding where they come from.
Si to put it simply : no repo name = default repo = "library"

**Comment by Haffon** [comment]
@NotGlop Thanks for you reply.
There is a docker registry been setup by our team. It's no any repository start with "library" in it when access it catalog by HTTP API, just something like "base/nginx".
I sill have some question want to ask:
1. When I push a tagged image to our team's private registry, if I use the "nginx-demo1" as its name, will this image be stored at "library" repo?
2. If I use "library/nginx-demo2", then what's the actually repo?
3. How about use "NotGlop/nginx-demo3"?

**Comment by NotGlop** [comment]
Unfortunately, the name of the archive (eg. toto_nginx.tar) has nothing to do with the name displayed in registries or in Docker client.

The strings used for this display are stored in the file named "repositories", within the TAR file. 

If you want to display another name, you should edit this file (although I do not recommand it, for compatibility purpose). 

If you explicitly push an image "library/nginx" on your custom registry then it will push the image "nginx", in the repo "library". 
If you push a "nginx" image (with no prefixed repository name), I honestly don't know the behavior; it may depend on the default repository configuration of your custom registry. 

Actually your question is pretty legitimate, but the behavior of such a scenario will be the same with a legit pull of an official nginx image (from Docker Hub), then a legit push of this same nginx image on a custom registry.

**Comment by Haffon** [comment]
@NotGlop This is very kindly for you reply, I'm learning cluster architecture which evolve some many things come from different area. It is hard to jump into it without knowing the bases.
