### ISSUE TITLE
Can't find velero's docker image

### ISSUE THREAD

**Issue by HoikanChan** [NotGlop/docker-drag#31]
Hello, thank you for the useful script, super appreciate that.

I got 404 when download velero. The dockehub url is  https://hub.docker.com/r/velero/velero

```sh
$ python3 docker_pull.py velero/velero
target is  https://registry-1.docker.io/v2/velero/velero/manifests/latest
[-] Cannot fetch manifest for velero/velero [HTTP 404]
b'{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes"}]}
```

**Comment by automationxpert** [comment]
same error while trying to download the target https://hub.docker.com/r/vaultwarden/server

```python
python docker_pull.py vaultwarden/server
```
[-] Cannot fetch manifest for vaultwarden/server [HTTP 404]
b'{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes"}]}\n'

But works for bitnami/suitecrm

**Comment by NotGlop** [comment]
Issue followed in #34 due to new OCI image manifest format.
Thank you for your feedbacks
