### ISSUE TITLE
[Feature Request] Update documentation to provide a sample for how to use the container after downloading it.

### ISSUE THREAD

**Issue by CDixon0416** [NotGlop/docker-drag#33]
First super useful tool, made use of it at work after finding it through a stackoverflow post. Thank you for making such a straightforward but functional tool.

Next, minor nitpick while docker load is contained within the main documentation for docker it might not hurt to throw the basic use case in the documentation so people will have some context for how to use this tool effectively.

**Comment by NotGlop** [comment]
Thank you for your feedback. The GIF in the README should be self-explanatory, but you are right, I will add text to make it clearer for CLI users only.
