### ISSUE TITLE
pulls from nvidia gpu cloud

### ISSUE THREAD

**Issue by atakanokan** [NotGlop/docker-drag#7]
First of all, thanks for the script!

However, I couldn't make it work for
```
docker pull nvcr.io/nvidia/tensorflow:19.10-py3
```
via:
```
python docker_pull.py nvcr.io/nvidia/tensorflow:19.05-py3
```

Error message:
```
Traceback (most recent call last):
  File "docker_pull.py", line 47, in <module>
    reg_service = resp.headers['WWW-Authenticate'].split('"')[3]
IndexError: list index out of range
```

**Comment by NotGlop** [comment]
Thank you for the issue, it helps to support particular use cases like this.
I have provided a fix for this in https://github.com/NotGlop/docker-drag/commit/249fc4f33fc5e0ad809a78c4fea2b8f69d7a8c60
`nvcr.io` registry is apparently handling authentication differently than registries I've encountered.

You should be able to download the image now. Please let me know if this fixes your issue.

PS: the label might not be properly displayed when doing `docker images` though.  
You might also have an "import reference" error, if this is the case please let me know as well.  
I am actually working on that bug.

**Comment by atakanokan** [comment]
Thank you @NotGlop ! Closing this issue and will open a new one, if any other error shows up.
