### ISSUE TITLE
[Feature Request] Progress bar using tqdm

### ISSUE THREAD

**Issue by atakanokan** [NotGlop/docker-drag#8]
It would be good to have a progress bar in this for loop: https://github.com/NotGlop/docker-drag/blob/249fc4f33fc5e0ad809a78c4fea2b8f69d7a8c60/docker_pull.py#L98-L144 

Maybe something like tqdm? https://github.com/tqdm/tqdm

**Comment by NotGlop** [comment]
Yes, I'm thinking of adding it with the stream download option proposed (amongst other ideas) in Pull Request https://github.com/NotGlop/docker-drag/pull/6
